"use client";

import { useEffect, useState } from "react";
import { Copy, Package, QrCode, ShieldCheck, Truck, X } from "@phosphor-icons/react";
import { toast } from "sonner";
import { PageShell } from "@/components/page-shell";

type Order={no:string;title:string;amount:string;status:string;kind:string;time:string};
const seed:Order[]=[{no:"BH202607310018",title:"日本 5G eSIM · 7天 10GB",amount:"¥88",status:"待激活",kind:"eSIM",time:"2026-07-31 15:28"},{no:"BH202607260096",title:"泰国 8 天上网卡 · 15GB",amount:"¥39",status:"运输中",kind:"实体卡",time:"2026-07-26 10:12"}];

export default function OrdersPage(){const [active,setActive]=useState("全部");const [orders,setOrders]=useState(seed);const [detail,setDetail]=useState<{order:Order;kind:"esim"|"shipping"}|null>(null);useEffect(()=>{try{const stored=JSON.parse(localStorage.getItem("buyhksim-orders")??"[]") as Order[];if(stored.length)setOrders([...stored,...seed])}catch{}},[]);const visible=orders.filter((order)=>active==="全部"||order.status.includes(active.replace("配送中","运输中")));const copy=async(no:string)=>{try{await navigator.clipboard.writeText(no);toast.success("订单号已复制")}catch{toast.error("浏览器未授权剪贴板，请手动复制")}};return <PageShell><main className="container-shell py-8"><h1 className="text-3xl font-black">我的订单</h1><p className="mt-2 quiet">查看支付、交付、物流与售后状态。</p><div className="mt-6 flex gap-2 overflow-x-auto pb-1">{["全部","待支付","待激活","配送中","已完成","售后中"].map((tab)=><button type="button" key={tab} onClick={()=>setActive(tab)} className={`shrink-0 rounded-lg px-4 py-2 text-sm ${active===tab?"bg-[var(--forest)] text-white":"surface"}`}>{tab}</button>)}</div><div className="mt-5 space-y-4">{visible.map((order)=><article key={order.no} className="surface rounded-xl p-5"><div className="flex flex-wrap justify-between gap-3 border-b border-[var(--line)] pb-3 text-sm"><span>订单号 {order.no} <button type="button" onClick={()=>copy(order.no)} aria-label="复制订单号" className="ml-1 align-middle"><Copy size={14}/></button></span><span className="quiet">{order.time}</span></div><div className="flex flex-col justify-between gap-4 pt-4 sm:flex-row sm:items-center"><div className="flex gap-3">{order.kind==="eSIM"?<QrCode size={38}/>:<Package size={38}/>}<span><b>{order.title}</b><p className="mt-1 text-sm quiet">{order.kind} · {order.status}</p></span></div><div className="flex flex-wrap items-center gap-3 sm:justify-end"><b>{order.amount}</b>{order.kind==="eSIM"?<button type="button" onClick={()=>setDetail({order,kind:"esim"})} className="rounded-lg bg-[var(--forest)] px-4 py-2 text-sm font-semibold text-white">安全领取 eSIM</button>:<button type="button" onClick={()=>setDetail({order,kind:"shipping"})} className="flex items-center gap-2 rounded-lg border border-[var(--line)] px-4 py-2 text-sm"><Truck size={18}/>查看物流</button>}</div></div></article>)}{!visible.length&&<div className="surface rounded-xl p-12 text-center quiet">当前分类暂无订单</div>}</div></main>{detail&&<Detail detail={detail} onClose={()=>setDetail(null)}/>}</PageShell>}

function Detail({detail,onClose}:{detail:{order:Order;kind:"esim"|"shipping"};onClose:()=>void}){return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4"><section role="dialog" aria-modal="true" aria-labelledby="order-detail-title" className="w-full max-w-lg rounded-2xl bg-[var(--surface)] p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold text-[var(--forest)]">ORDER DETAIL</p><h2 id="order-detail-title" className="mt-1 text-xl font-black">{detail.kind==="esim"?"eSIM 安全领取":"物流轨迹"}</h2></div><button type="button" onClick={onClose} aria-label="关闭"><X size={24}/></button></div>{detail.kind==="esim"?<div className="mt-5"><div className="rounded-xl bg-[var(--forest-wash)] p-5 text-center"><ShieldCheck size={46} className="mx-auto text-[var(--forest)]"/><b className="mt-3 block">需要二次验证</b><p className="mt-2 text-sm quiet">生产环境将验证登录会话与一次性验证码，二维码领取行为会写入审计日志。</p></div><button type="button" onClick={()=>toast.info("沙箱不会展示真实 eSIM 密钥；二次验证流程已触发")} className="mt-4 w-full rounded-lg bg-[var(--forest)] py-3 font-semibold text-white">发送验证码并继续</button></div>:<ol className="mt-5 space-y-4 border-l-2 border-[var(--line)] pl-5"><li><b>运输中</b><p className="text-sm quiet">今天 08:32 · 已离开深圳转运中心</p></li><li><b>已揽收</b><p className="text-sm quiet">昨天 19:10 · 顺丰速运已揽件</p></li><li><b>订单已出库</b><p className="text-sm quiet">昨天 17:45 · 香港数字仓</p></li></ol>}<button type="button" onClick={onClose} className="mt-5 w-full rounded-lg border border-[var(--line)] py-2.5">关闭</button></section></div>}
