import { BadRequestException,Inject,Injectable,ServiceUnavailableException } from "@nestjs/common";import { randomUUID } from "node:crypto";import type { Sql } from "postgres";import { DB_CLIENT } from "../../shared/database.module";
@Injectable() export class OperationsService{constructor(@Inject(DB_CLIENT) private readonly client:Sql|null){}private db(){if(!this.client)throw new ServiceUnavailableException("运营数据库尚未配置");return this.client}async list(merchantId:string,section:string,view:number){if(!merchantId)throw new BadRequestException("当前账户未绑定商户");if(!Number.isInteger(view)||view<0||view>3)throw new BadRequestException("视图参数无效");const sql=this.db();let rows:readonly unknown[]=[];
    if(section==="orders")rows=await sql`select o.id,coalesce((select string_agg(oi.title_snapshot,' / ') from order_items oi where oi.order_id=o.id),'订单') as name,o.order_no as reference,o.status,'' as owner,o.updated_at as "updatedAt" from orders o where o.merchant_id=${merchantId} and (${view}=0 and o.status='PENDING_PAYMENT' or ${view}=1 and o.status in ('PAID','FULFILLING') or ${view}=2 and o.status in ('CLOSED','AFTER_SALE','REFUNDED') or ${view}=3 and exists(select 1 from shipments sh where sh.order_id=o.id)) order by o.updated_at desc limit 500`;
    else if(section==="inventory")rows=view===2?await sql`select id,name,code as reference,kind as status,'' as owner,updated_at as "updatedAt" from warehouses where merchant_id=${merchantId} order by updated_at desc`:view===1?await sql`select r.id,p.title as name,s.code as reference,r.status,w.name as owner,r.updated_at as "updatedAt" from inventory_reservations r join skus s on s.id=r.sku_id join products p on p.id=s.product_id join warehouses w on w.id=r.warehouse_id where p.merchant_id=${merchantId} order by r.updated_at desc limit 500`:view===0?await sql`select concat(s.id,'-',i.warehouse_id) as id,p.title as name,s.code as reference,concat('可用 ',i.available,' / 锁定 ',i.locked,' / 已售 ',i.sold) as status,w.name as owner,i.updated_at as "updatedAt" from inventory i join skus s on s.id=i.sku_id join products p on p.id=s.product_id join warehouses w on w.id=i.warehouse_id where p.merchant_id=${merchantId} order by i.updated_at desc limit 500`:[];
    else if(section==="after-sales")rows=await sql`select a.id,concat(a.type,' · ',left(a.reason,80)) as name,o.order_no as reference,a.status,coalesce(u.display_name,u.email,'') as owner,a.updated_at as "updatedAt" from after_sales a join orders o on o.id=a.order_id left join users u on u.id=a.user_id where o.merchant_id=${merchantId} order by a.updated_at desc limit 500`;
    else if(section==="customers")rows=view===0?await sql`select id,coalesce(display_name,email) as name,email as reference,status,membership_level as owner,updated_at as "updatedAt" from users where merchant_id=${merchantId} order by updated_at desc limit 500`:view===2?await sql`select pl.id,coalesce(u.display_name,u.email) as name,pl.reference_id as reference,concat(pl.change,' / ',pl.reason) as status,'' as owner,pl.created_at as "updatedAt" from point_ledger pl join users u on u.id=pl.user_id where u.merchant_id=${merchantId} order by pl.created_at desc limit 500`:[];
    else if(section==="distribution")rows=view===1?await sql`select c.id,coalesce(u.display_name,u.email) as name,oi.id::text as reference,concat(c.status,' · ',c.amount_minor,' ',c.currency) as status,'' as owner,c.updated_at as "updatedAt" from commissions c join users u on u.id=c.beneficiary_id join order_items oi on oi.id=c.order_item_id join orders o on o.id=oi.order_id where o.merchant_id=${merchantId} order by c.updated_at desc limit 500`:view===2?await sql`select w.id,coalesce(u.display_name,u.email) as name,w.id::text as reference,concat(w.status,' · ',w.amount_minor,' ',w.currency) as status,'' as owner,w.updated_at as "updatedAt" from withdrawals w join users u on u.id=w.user_id where u.merchant_id=${merchantId} order by w.updated_at desc limit 500`:[];
    else if(section==="finance")rows=view===0?await sql`select p.id,o.order_no as name,coalesce(p.channel_transaction_id,p.id::text) as reference,concat(p.status,' · ',p.amount_minor,' ',p.currency) as status,p.channel as owner,p.updated_at as "updatedAt" from payments p join orders o on o.id=p.order_id where o.merchant_id=${merchantId} order by p.updated_at desc limit 500`:view===1?await sql`select r.id,o.order_no as name,coalesce(r.channel_refund_id,r.id::text) as reference,concat(r.status,' · ',r.amount_minor) as status,'' as owner,r.updated_at as "updatedAt" from refunds r join orders o on o.id=r.order_id where o.merchant_id=${merchantId} order by r.updated_at desc limit 500`:view===2?await sql`select id,channel as name,id::text as reference,concat(status,' · 差异 ',mismatch_count) as status,'' as owner,updated_at as "updatedAt" from reconciliation_results order by updated_at desc limit 500`:[];
    else if(section==="security")rows=view===2?await sql`select id,action as name,coalesce(target_id,'') as reference,target_type as status,coalesce(actor_id::text,'SYSTEM') as owner,created_at as "updatedAt" from audit_logs where merchant_id=${merchantId} order by created_at desc limit 500`:view===3?await sql`select r.id,r.kind as name,r.request_id as reference,concat(r.decision,' · ',r.score) as status,coalesce(r.user_id::text,'') as owner,r.created_at as "updatedAt" from risk_events r left join users u on u.id=r.user_id where u.merchant_id=${merchantId} or r.user_id is null order by r.created_at desc limit 500`:[];
    else if(!["marketing","settings"].includes(section))throw new BadRequestException("运营模块不存在");
    return {ok:true,data:rows,requestId:randomUUID()};}
    async overview(merchantId:string){if(!merchantId)throw new BadRequestException("当前账户未绑定商户");const rows=await this.db()<Array<{revenue:number;paid_orders:number;pending_fulfillment:number;active_products:number}>>`select coalesce(sum(total_minor) filter(where status in ('PAID','FULFILLING','COMPLETED')),0)::int as revenue,count(*) filter(where status in ('PAID','FULFILLING','COMPLETED'))::int as paid_orders,count(*) filter(where status='PAID')::int as pending_fulfillment,(select count(*)::int from products where merchant_id=${merchantId} and status='ACTIVE') as active_products from orders where merchant_id=${merchantId} and created_at>=date_trunc('day',now())`;return {ok:true,data:rows[0]??{revenue:0,paid_orders:0,pending_fulfillment:0,active_products:0},requestId:randomUUID()}}
}
